# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

taxi_transform:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      threads: 4
      schema: analytics

  target: dev
